SELECT U.USER_ID, U.NICKNAME, concat(U.CITY, concat(' ', concat(U.STREET_ADDRESS1, concat(' ', U.STREET_ADDRESS2)))) AS 전체주소, concat(substr(U.TLNO,1,3),'-',substr(U.TLNO,4,4),'-',substr(U.TLNO,8,4))AS 전화번호
FROM USED_GOODS_BOARD B RIGHT JOIN USED_GOODS_USER U ON B.WRITER_ID = U.USER_ID
GROUP BY B.WRITER_ID
HAVING COUNT(B.WRITER_ID) >= 3
ORDER BY U.USER_ID DESC;