-- 코드를 입력하세요
SELECT B.WRITER_ID AS USER_ID, F.NICKNAME, SUM(B.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD B RIGHT JOIN USED_GOODS_USER F ON B.WRITER_ID = F.USER_ID
WHERE B.STATUS = 'DONE'
GROUP BY B.WRITER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES ASC;